service: codebuddy

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

functions:
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  createRoom:
    handler: handler.createRoom
    events:
      - http:
          path: room
          method: post
          cors: true

  getOneUser:
    handler: handler.getOneUser
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  getAllUsers:
    handler: handler.getAllUsers
    events:
      - http:
          path: user
          method: get
          cors: true

  getRooms:
    handler: handler.getRooms
    events:
      - http:
          path: room/{id}
          method: get
          cors: true

  getAllRooms:
    handler: handler.getAllRooms
    events:
      - http:
          path: room
          method: get
          cors: true

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  updateRoom:
    handler: handler.updateRoom
    events:
      - http:
          path: room/{id}
          method: put
          cors: true

  deleteRoom:
    handler: handler.deleteRoom
    events:
      - http:
          path: room/{id}
          method: delete
          cors: true

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

plugins:
  - serverless-offline
